version: '3.7'
services:
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DATABASE: customer
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_HOST: postgres_db
    command: start-dev
    ports:
      - 8080:8080
    volumes:
      - keycloak-data:/opt/keycloak/data
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  keycloak-data:
